### ISSUE TITLE
various compile errors

### ISSUE THREAD

**Issue by mechpil0t** [magicleap/MagicLeapUnitySDK#1]
Unity 2020.1.10f
Magic Leap XR Plugin 5.1.2

```
Assets\MagicLeap\Lumin\APIs\MLResult.cs(1238,58): error CS1503: Argument 1: cannot convert from 'string' to 'System.IntPtr'

Assets\MagicLeap\Lumin\Bindings\MLMeshingNativeBindings.cs(499,95): error CS1503: Argument 1: cannot convert from 'UnityEngine.Vector3' to 'float'

Assets\MagicLeap\Lumin\Bindings\MLMeshingNativeBindings.cs(499,136): error CS1503: Argument 1: cannot convert from 'UnityEngine.Vector3' to 'float'

Assets\MagicLeap\Lumin\Bindings\MLMeshingNativeBindings.cs(516,69): error CS1503: Argument 1: cannot convert from 'UnityEngine.Vector3' to 'float'
```

**Comment by Nihav-Jain** [comment]
Hi @FriskyBishop, the fixes have been merged into master and a new pre-release has been cut - https://github.com/magicleap/MagicLeapUnitySDK/releases/tag/0.24.2Exp-2
Please let us know if you run into any other issues.

**Comment by Nihav-Jain** [comment]
We are making a number of changes in our internal development and release processes to ensure future updates are cleaner and bug free. We appreciate your patience.
