### ISSUE TITLE
The link leads to Page not found

### ISSUE THREAD

**Issue by TimmyBest** [magicleap/MagicLeapUnitySDK#8]
The link leads to Page not found
[[this page on the Magic Leap Developer Portal](https://developer.magicleap.com/en-us/learn/guides/unity-overview)](url)

<img width="1075" alt="Screenshot 2023-03-07 at 18 43 44" src="https://user-images.githubusercontent.com/25765075/223505168-db01c473-5785-4caa-9c63-b49aee6b3cbf.png">
<img width="2548" alt="Screenshot 2023-03-07 at 18 43 05" src="https://user-images.githubusercontent.com/25765075/223505176-99bff8e7-45ff-4b11-9cfd-8a2e6f55047c.png">

**Comment by MadeinPh1la** [comment]
Thank you for raising this issue, we fixed the link
